### ISSUE TITLE
IsolateState can not work with coroutines MutableStateFlow: kotlin.native.concurrent.FreezingException: freezing of Ok(result=kotlinx.coroutines.flow.StateFlowImpl@80804878) has failed, first blocker is kotlinx.coroutines.flow.StateFlowImpl@80804878

### ISSUE THREAD

**Issue by xiaobailong24** [touchlab/Stately#71]
org.jetbrains.kotlinx:kotlinx-coroutines-core:1.5.1-native-mt

iosTest sorceset:
```kotlin

import kotlinx.coroutines.*
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.flow.collect
import kotlin.coroutines.CoroutineContext
import kotlin.test.Test

// https://github.com/Kotlin/kotlinx.coroutines/issues/1996
//iOS code:
val testCoroutineContext: CoroutineContext =
    newSingleThreadContext("testRunner")

fun runBlockingTest(block: suspend CoroutineScope.() -> Unit) =
    runBlocking(testCoroutineContext) { this.block() }

class IsoStateTest {

    private val flowState =
        IsolateState {
            MutableStateFlow("")
        }

    @OptIn(ExperimentalCoroutinesApi::class)
    @Test
    fun test() = runBlockingTest {
        println("runBlockingTest start")
        val job = launch {
            flowState
                .access { it }
                .asStateFlow().collect {
                    run()
                }
        }

        flowState.access { it.value = "123" }

//        job.cancel()
        println("runBlockingTest end")
    }

    private suspend fun run() {
        println("collect:${flowState.access { it.value }}")
    }
}
```

got error:
```
runBlockingTest start
runBlockingTest end

kotlin.native.concurrent.FreezingException: freezing of Ok(result=kotlinx.coroutines.flow.StateFlowImpl@80804878) has failed, first blocker is kotlinx.coroutines.flow.StateFlowImpl@80804878
kotlin.native.concurrent.FreezingException: freezing of Ok(result=kotlinx.coroutines.flow.StateFlowImpl@80804878) has failed, first blocker is kotlinx.coroutines.flow.StateFlowImpl@80804878
	at kotlin.Throwable#<init>(/Users/teamcity1/teamcity_work/7c4fade2802b7783/kotlin/kotlin-native/runtime/src/main/kotlin/kotlin/Throwable.kt:23)
	at kotlin.Exception#<init>(/Users/teamcity1/teamcity_work/7c4fade2802b7783/kotlin/kotlin-native/runtime/src/main/kotlin/kotlin/Exceptions.kt:23)
	at kotlin.RuntimeException#<init>(/Users/teamcity1/teamcity_work/7c4fade2802b7783/kotlin/kotlin-native/runtime/src/main/kotlin/kotlin/Exceptions.kt:34)
	at kotlin.native.concurrent.FreezingException#<init>(/Users/teamcity1/teamcity_work/7c4fade2802b7783/kotlin/kotlin-native/runtime/src/main/kotlin/kotlin/native/concurrent/Freezing.kt:15)
	at <global>.ThrowFreezingException(/Users/teamcity1/teamcity_work/7c4fade2802b7783/kotlin/kotlin-native/runtime/src/main/kotlin/kotlin/native/concurrent/Internal.kt:88)
	at <global>.FreezeSubgraph(Unknown Source)
	at <global>.Kotlin_Worker_freezeInternal(Unknown Source)
	at kotlin.native.concurrent#freeze__at__0:0(/Users/teamcity1/teamcity_work/7c4fade2802b7783/kotlin/kotlin-native/runtime/src/main/kotlin/kotlin/native/concurrent/Freezing.kt:33)
	at co.touchlab.stately.isolate.BackgroundStateRunner.stateRun$lambda-1#internal(co.touchlab.stately.isolate/BackgroundStateRunner.kt:15)
	at <global>._ZN6Worker19processQueueElementEb(Unknown Source)
	at <global>._ZN12_GLOBAL__N_113workerRoutineEPv(Unknown Source)
	at <global>._pthread_start(Unknown Source)
	at <global>.thread_start(Unknown Source)

```

**Comment by xiaobailong24** [comment]
https://github.com/Kotlin/kotlinx.coroutines/issues/2584

**Comment by kpgalligan** [comment]
This code directly violates the basic concept of `IsolateState`.

```kotlin
flowState
      .access { it }
```

The thing that's kept isolated, `MutableStateFlow("")`, has `ensureNeverFrozen()` called on it when you init the `IsolateState` instance (https://github.com/touchlab/Stately/blob/main/stately-isolate/src/nativeCommonMain/kotlin/co/touchlab/stately/isolate/Platform.kt#L15).

The exception is happening because when you try to return the `MutableStateFlow` instance in the above code, it needs to be frozen as per K/N memory model rules, but you can't (because `ensureNeverFrozen()` ). 

As for what you should do instead, I'm not sure. Flows are freezable, generally speaking. The bug you linked is old and fixed.

**Comment by xiaobailong24** [comment]
@kpgalligan Thanks for your replay. But how to use MutableStateFlow with IsolateState please?

**Comment by xiaobailong24** [comment]
Use `Result` wrapper the flow to solve the ploblem:

```
 private val flowState =
        IsolateState {
            Result.success(MutableStateFlow("1"))
        }


    @OptIn(ExperimentalCoroutinesApi::class)
    @Test
    fun test() = runBlockingTest {
        println("runBlockingTest start")
        val job = launch {
            flowState
                .access {
                    it.getOrNull()!!
                }
                .asStateFlow()
                .collect {
                    run()
                }
        }

        flowState.access { it.getOrNull()?.value = "123" }

//        job.cancel()
        println("runBlockingTest end")
    }

    private suspend fun run() {
        println("collect:${flowState.access { it.getOrNull()?.value }}")
    }
```

**Comment by kpgalligan** [comment]
Why are you using `IsolateState` at all in that case? The `MutableStateFlow` instance will be frozen. Try this:

```kotlin
private val flowState = MutableStateFlow("1")

    @OptIn(ExperimentalCoroutinesApi::class)
    @Test
    fun test() = runBlockingTest {
        println("runBlockingTest start")
        val job = launch {
            flowState
                .asStateFlow()
                .collect {
                    run()
                }
        }

        flowState.value = "123"

//        job.cancel()
        println("runBlockingTest end")
    }

    private suspend fun run() {
        println("collect:${flowState.value}")
    }
```

**Comment by xiaobailong24** [comment]
Because the MutableStateFlow instance may be access to get or set new value in multi-thread.

**Comment by xiaobailong24** [comment]
@kpgalligan 
`access()` block param will block main thread in iOS platform?
```
fun test() {
        val map = IsolateState{ mutableMapOf<Int,String>()}
        map.access { _map->
            // will block main thread?
            repeat(100_1000){
                _map[it] = "$it"
            }
        }
    }
```

**Comment by kpgalligan** [comment]
Yes, until your loop is done. IsolateState isn't async and access isn't a suspend.

**Comment by xiaobailong24** [comment]
Is there a workaround to handle time-consuming task and don't block main thread?
